apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: 730335644951.dkr.ecr.ap-south-1.amazonaws.com/app1:amd64
        ports:
        - containerPort: 8080
        env:
        - name: APP2_IP
          value: "app2-service"
        - name: APP2_PORT
          value: "80"